apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: background-colour-app
  name: background-colour-nfs
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
